<?php

namespace AppBundle\Repository;

/**
 * AnalisisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalisisRepository extends \Doctrine\ORM\EntityRepository
{
}
